import{S as m,i,a as g}from"./assets/vendor-DzBlEn4a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const c=document.querySelector(".loader"),f=document.querySelector(".gallery"),h=new m(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function y(s){const t=s.map(({webformatURL:r,largeImageURL:n,tags:e,likes:o,views:a,comments:d,downloads:p})=>`
    <li class="gallery-item">
        <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${r}" alt="${e}" />
        </a>
        <div class="gallery-image-data">
            <p class="data-text"><span class="bold">Likes</span> ${o}</p>
            <p class="data-text"><span class="bold">Views</span> ${a}</p>
            <p class="data-text"><span class="bold">Comments</span> ${d}</p>
            <p class="data-text"><span class="bold">Downloads</span> ${p}</p>
        </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",t),h.refresh()}function b(){i.show({title:"Sorry",message:", there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}function L(){f.innerHTML=""}function S(){c.classList.remove("hidden")}function l(){c.classList.add("hidden")}document.querySelector(".form");const q="https://pixabay.com/api/",w="52805725-7d516d36c1804a9cebba9806b";function x(s){return g(q,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:18}}).then(t=>t.data.hits.length>0?t.data.hits:(b(),null)).catch(t=>i.show({message:t.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})).finally(()=>{l()})}const u=document.querySelector(".form"),C=u.querySelector('input[name="search-text"]');u.addEventListener("submit",v);function v(s){s.preventDefault();const t=C.value;if(!t.trim().length){i.show({message:"Input field is empty",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"}),l();return}L(),S(),x(t).then(r=>{r&&y(r)}).catch(r=>i.show({message:r.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})),l(),s.target.reset()}
//# sourceMappingURL=index.js.map
