import{S as y,i as u,a as h}from"./assets/vendor-xwsNXkQR.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const d=document.querySelector(".loader"),f=document.querySelector(".gallery"),b=new y(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function L(a){const o=a.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:s,comments:m,downloads:g})=>`
    <li class="gallery-item">
        <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${r}" alt="${e}" />
        </a>
        <div class="gallery-image-data">
            <p class="data-text"><span class="bold">Likes</span> ${t}</p>
            <p class="data-text"><span class="bold">Views</span> ${s}</p>
            <p class="data-text"><span class="bold">Comments</span> ${m}</p>
            <p class="data-text"><span class="bold">Downloads</span> ${g}</p>
        </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),b.refresh()}function S(){u.show({title:"Sorry",message:", there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}function x(){f.innerHTML=""}function l(){d.classList.remove("hidden")}function i(){d.classList.add("hidden")}const q=document.querySelector(".form"),v=q.querySelector('input[name="search-text"]'),$="https://pixabay.com/api/",w="52805725-7d516d36c1804a9cebba9806b";v.value;function P(a){return h($,{params:{key:w,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data.hits.length>0?r.data.hits:(S(),null)).catch(r=>u.show({message:r.message,position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})).finally(()=>{i()})}const p=document.querySelector(".form"),c=p.querySelector('input[name="search-text"]');p.addEventListener("submit",O);function O(a){if(a.preventDefault(),l(),x(),!c.value.trim()){i();return}l(),P(c.value).then(o=>{o&&L(o)}),i(),a.target.reset()}
//# sourceMappingURL=index.js.map
