import{S as d,i as p,a as f}from"./assets/vendor-D8hBcPQM.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const l=document.querySelector(".loader"),m=document.querySelector(".gallery");function y(r){return r.map(({webformatURL:o,largeImageURL:s,tags:n,likes:e,views:t,comments:a,downloads:u})=>`
    <li class="gallery-item">
        <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${o}" alt="${n}" />
        </a>
        <p><span class="bold">Likes</span> ${e}</p>
        <p><span class="bold">Views</span> ${t}</p>
        <p><span class="bold">Comments</span> ${a}</p>
        <p><span class="bold">Downloads</span> ${u}</p>
    </li>`).join("")}function g(){p.show({title:"Sorry",message:", there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fffc3aff",backgroundColor:"#ec3939"})}function h(){m.innerHTML=""}function b(){l.classList.remove("hidden")}function L(){l.classList.add("hidden")}new d(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});const S="https://pixabay.com/api/",i=document.querySelector(".gallery");function q(r){f(S,r).then(o=>{o.data.hits.length>0?(i.innerHTML=y(o.data.hits),i.refresh()):g()}).catch(o=>console.log(o)).finally(()=>{L()})}const $="52805725-7d516d36c1804a9cebba9806b",c=document.querySelector(".form"),P=c.querySelector('input[name="search-text"]');c.addEventListener("submit",v);function v(r){r.preventDefault(),b();const o=P.value,s={params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}};h(),q(s)}
//# sourceMappingURL=index.js.map
